version: '3'
services:
  api:
    container_name: synod-api
    image: synod
    ports:
      - '5555:5555'
    environment:
      - SYNOD_APP_ID=0
      - SYNOD_API_ADDR=127.0.0.1:5555
      - SYNOD_DATA_ADDR=:5566
    networks:
      - synod-inner
    depends_on:
      - etcd
      - es
  data1:
    container_name: synod-data-1
    image: synod
    environment:
      - SYNOD_APP_ID=1
      - SYNOD_API_ADDR=:5555
      - SYNOD_DATA_ADDR=:5566
    command: [ '/synod', '-c', 'var/synod.docker.yml', 'run', 'data' ]
    networks:
      - synod-inner
    depends_on:
      - etcd
      - es
  data2:
    container_name: synod-data-2
    image: synod
    environment:
      - SYNOD_APP_ID=2
      - SYNOD_API_ADDR=:5555
      - SYNOD_DATA_ADDR=:5566
    command: [ '/synod', '-c', 'var/synod.docker.yml', 'run', 'data' ]
    networks:
      - synod-inner
    depends_on:
      - etcd
      - es
  data3:
    container_name: synod-data-3
    image: synod
    environment:
      - SYNOD_APP_ID=3
      - SYNOD_API_ADDR=:5555
      - SYNOD_DATA_ADDR=:5566
    command: [ '/synod', '-c', 'var/synod.docker.yml', 'run', 'data' ]
    networks:
      - synod-inner
    depends_on:
      - etcd
      - es
  data4:
    container_name: synod-data-4
    image: synod
    environment:
      - SYNOD_APP_ID=4
      - SYNOD_API_ADDR=:5555
      - SYNOD_DATA_ADDR=:5566
    command: [ '/synod', '-c', 'var/synod.docker.yml', 'run', 'data' ]
    networks:
      - synod-inner
    depends_on:
      - etcd
      - es
  data5:
    container_name: synod-data-5
    image: synod
    environment:
      - SYNOD_APP_ID=5
      - SYNOD_API_ADDR=:5555
      - SYNOD_DATA_ADDR=:5566
    command: [ '/synod', '-c', 'var/synod.docker.yml', 'run', 'data' ]
    networks:
      - synod-inner
    depends_on:
      - etcd
      - es
  data6:
    container_name: synod-data-6
    image: synod
    environment:
      - SYNOD_APP_ID=6
      - SYNOD_API_ADDR=:5555
      - SYNOD_DATA_ADDR=:5566
    command: [ '/synod', '-c', 'var/synod.docker.yml', 'run', 'data' ]
    networks:
      - synod-inner
    depends_on:
      - etcd
      - es
  es:
    container_name: synod-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    networks:
      - synod-inner
  etcd:
    container_name: synod-etcd
    image: bitnami/etcd:3
    environment:
      - ETCD_NAME=node1
      - ALLOW_NONE_AUTHENTICATION=yes
    networks:
      - synod-inner
networks:
  synod-inner:
