app:
  id: 1
  debug: true
  env: dev
storage:
  addr: 127.0.0.1:5566
  workdir: /Users/fatrbaby/workspaces/golang/synod/var/disk
api:
  addr: 127.0.0.1:5555
etcd:
  dialTimeout: 2
  endpoints:
    - 127.0.0.1:2379
meta:
  use: es
  elasticsearch:
    endpoints:
      - http://127.0.0.1:9200
    username:
    password: